### ISSUE TITLE
Publish Early Access 1.0 MVP to itch.io via Butler

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#126]
Publish the latest iteration of Early Access 1.0 (v 0.1.2-0223) to itch.io via Butler:

Background:
[Introduction to Butler](https://itch.io/docs/butler/)

**Comment by DragoonHP** [comment]
Done!

**Comment by kwangchow** [comment]
Works a treat, awesome job :)
