### ISSUE TITLE
Confirm Early Access Visual Assets

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#127]
Would it be possible to write a script which would tell me:
- What visual assets are used in Early Access 1.0?
- Where they are used (eg. Main Menu, Play Scene, etc)?
- Their file type (eg. .png)?
- Their dimensions (eg. 20x20)
- Their project path (eg. .../Founders-Life--New-Prototype/game/images/icons/crab-512.png)

This would be a real timesaver as I pull together a visual brief. It will also help ensure standards - formats, naming conventions, file sizes, etc - are maintained.

**Comment by DragoonHP** [comment]
So I added something for this in the latest release.

Start the game. And select "Image Data" on the lower left of the screen. Give it a few seconds to load.
![Image screen](https://user-images.githubusercontent.com/1311129/36681426-9ebdc464-1b3e-11e8-9a66-05ed3b223656.png)

* Click on the black buttons containing the details to see the image.
* Click and drag (or scroll) on the transparent area to see all the entries

**Comment by kwangchow** [comment]
Amazing, is there a way to spit a full list out as a debug file (.csv, if possible)?

**Comment by DragoonHP** [comment]
Can you work with json? (it's much easier to export to json).

If yes, the new commit includes a save button. If no, let me know

**Comment by kwangchow** [comment]
Yep, that's perfect, it's easy to locally convert data from json to csv.

Update: conversion works fine, nice one.
