### ISSUE TITLE
Add Roadmap section to cover

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#130]
1. Reposition Quit button (see screenshot)
![roadmap01](https://user-images.githubusercontent.com/7693171/39756306-13a7b942-52da-11e8-8110-49668b0eb3a4.png)

2. Add Roadmap icon (see screenshot). File attached.
![roadmap02](https://user-images.githubusercontent.com/7693171/39756348-47072f52-52da-11e8-9e45-df6a900d34b4.png)

[Roadmap.zip](https://github.com/NellWatson/Founders-Life--New-Prototype/files/1983785/Roadmap.zip)

3. Add Roadmap section:
a. Founderpedia achievements section 
- Presented as per in-game scene.

b. Founder Hall of Fame.
- A local leaderboard of every full play through of Founder Life (ie. game complete or game over).
- Presented in a simple arcade style
Date. Founder Name. Days Survived. Founder XP
- See wireframe below

Date | Founder Name | Days Survived | Founder Score
--- | --- | ---| ---
#DATE | #NAME | #DAYS | #SCORE
20-May-18 | Sean | 24 | 10,456
18-April-18 | ST | 10 | 5,874

Notes: 
- achievements unlocked/locked should be persistent (eg. a reflection of total play, not local to any game).
- neither Founderpedia or Founder Hall of Fame are reset when player resets in-game save data via Settings

**Comment by DragoonHP** [comment]
A question.

* What exactly should the roadmap display (except the in-game achievements)?

**Comment by kwangchow** [comment]
For now, only two pages:
a. Founderpedia (lifetime)
b. Hall of Fame (lifetime local leaderboard)

Both as described above.

Eventually, I think it would be good to expand it with some macro performance analytics (represented as a radar/spider chart, perhaps) but I figured we may as well hold off until we have a feel for what aspects of performance are worth measuring in Alpha 1.0.

So that'll be a job for Alpha 1.1, as will switching the leaderboards from local to global.

Does that make sense?

**Comment by kwangchow** [comment]
Note: the "Roadmap" label is probably misleading now (given the overlap with in-game session-specific performance/progress) - should we just refer to it as Founder Stats?

**Comment by DragoonHP** [comment]
Yeah, we should. I was really confused when you said Roadmap and hence the question.

Also, how should we display which screen to show (Founderpedia and Hall of Fame) when player clicks on the "Roadmap" icon?

**Comment by kwangchow** [comment]
Right, it's agreed, let's never speak of "Roadmap" again :)

Yes. Founderpedia is already displayed on the achievements page, so if we could do similar for Hall of Game, that would be great. 

We can re-use the forward/back arrows we use for the end-of-game survey for navigation too.

**Comment by DragoonHP** [comment]
Alright. I'll whip up something :)

**Comment by DragoonHP** [comment]
Sorry it took a while to close this.

It was a bit more involved then I first assumed and I found two more bugs that needed to be fixed. Anyways, it's fixed now.
