### ISSUE TITLE
Add 'Performance Review' for Game Over

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#132]
At the moment, you don't get a final score/performance review when you die.

Can we add a Performance Review? It should work as per end-of-sprint review, using your final KPI scores rather than your end-of-sprint KPI scores.

**Comment by DragoonHP** [comment]
I'm not exactly sure how I should show it. (Currently End of sprint review shows the four KPI and their end of week values and then the next screen shows the points earned in the last week and total point).

**Comment by kwangchow** [comment]
I think we should stay as closely to the established review ceremony as possible. The only difference (for a first pass) should be one variable is at zero, so nothing is awarded.

After your totals are shown then the game ends (it will help contextualise the local leaderboard).

Does that make sense?

**Comment by DragoonHP** [comment]
Yes, that does. Thanks a lot :)
