### ISSUE TITLE
Refactor event variables 

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#135]
Each event should be structured with the following variables:
* Event ID (ie. chapter_01_05)
* Event Category (ie. energy)
* Character (ie. Eileen)
* Conditions [see below]
* Description (ie. "With your current pace, there is no way that the MVP is going to ship to the schedule you promised interested investors. Pressure the team to crunch some nights and weekends?")

Yes (ie. $ variable("productivity", 10), $ variable("energy", -20), $ variable("morale", -20), $ variable("affection", -1)

No (ie. $ variable("productivity", -10), $ variable("energy", 20), $ variable("morale", 20), $ variable ("affection", 2)

Note: see for #134 for Affection variable context

**Conditions**
Task: Add Conditions to the event variables.

Details:
- Events with a blank Conditions variable can be triggered at any time.
- Events with a specific Condition can only be triggered when specified conditions are met, eg:
$ variable("Conditions", eileen-affection <= 10)
[Present this event to player only if Eileen's affection level is less than or equal to 10]

$ variable("Conditions", energy >= 50)
[Present this event to player only if player's energy level is greater than or equal to 50]

**Comment by DragoonHP** [comment]
Hey Sean

A confirmation; will we still show only one dialogue before and after the choice or will we show more? I'm redesigning the event bucket.

Example event block:
```
    menu:
        e "With your current pace, there is no way that the MVP is going to ship to the schedule you promised interested investors. Pressure the team to crunch some nights and weekends?"

        "$_YES":
            $ variable("productivity", 10)
            $ variable("energy", -20)
            $ variable("morale", -20)

        "$_NO":
            $ variable("productivity", -10)
            $ variable("energy", 20)
            $ variable("morale", 20)
```

**Comment by kwangchow** [comment]
Hey. Yes, let's keep that as it currently is for a first pass.

**Comment by DragoonHP** [comment]
Alright. I'll be overhauling the entire label based event system and replacing it with individual json files. It should allow us to load in new events as needed from hard-disk or web.

**Comment by DragoonHP** [comment]
One last thing, are we dropping the major | minor event structure?

**Comment by kwangchow** [comment]
Event structure: yes, let's drop the major/minor component.

Re: categories, I'm not sure, it will depend on what Cara wants - can we make it editable and 'comment it out' for now (with a view to it possibly coming back in future)?

**Comment by DragoonHP** [comment]
>Event structure: yes, let's drop the major/minor component.
Will drop support for it then.

>Re: categories, I'm not sure, it will depend on what Cara wants - can we make it editable and 'comment it out' for now (with a view to it possibly coming back in future)?
Since I'm redoing the whole event code, I will leave some hooks in case we want to forbid same catergory events from showing up in consecutive weeks.

For now, same category events can show up back to back (which incidentally makes my work easier too)
