### ISSUE TITLE
Add a second description tag to events

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#136]
Can we add a second description tag to events, eg:
"description_01": "Yada yada",
"description_02": "Yada yada yada",

This additional tag should be optional, it won't be used in all events, therefore:

If description_02 contains text then it is displayed immediately after the "description_01" text, eg:
"description_02": "Yada yada yada" 
= Yada yada yada (in game)

If description_02 contains no quoted text - a zero instead? -then only description_01 is displayed and description_02 is ignored/bypassed, eg:
"description_02": 0
= [skip] (in game)

Does that make sense and/or work?

**Comment by DragoonHP** [comment]
So after testing out a couple of methods, I decided to make the description key entires a list to allow for multiple dialogue strings.

```
    "description": {
        "en": ["Honey... can we talk? The thing is, you never gave me a chance to agree to you trying to have a startup. But this affects me as well - if you quit your job and this doesn't pan out, we'll be living off of my income.", "I know we've only been dating for eight months, so it's hard for me to say this. It makes our relationship so serious. But we do live together. And if we're going to be together long-term, what you do affects me, and what I do affects you.", "I'm trying my hardest to be supportive of your dream, but... this isn't something you should've approached as if I don't exist. I just wanted you to know that.", "If you work hard, then I'll try my hardest, too. But cut me some slack as well, okay?"}
    },
```
