### ISSUE TITLE
v 0.1.4-0731 Minor Issues

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#139]
- [x] #Name is not working in the new engine (see screenshot below)
![screen shot 2018-08-01 at 11 10 14](https://user-images.githubusercontent.com/7693171/43516010-165d289a-957c-11e8-8eca-9c8706f7662e.png)

- [ ] Events repeat themselves

**Comment by DragoonHP** [comment]
>Events repeat themselves
Should the events not repeat ever?

**Comment by kwangchow** [comment]
Ideally, not. As per [Requirements](https://github.com/NellWatson/Founders-Life--New-Prototype/wiki/Alpha-1.0-Gameplay-Requirements#events):
"When an event has been used in play, it is discarded (i.e. no events are repeated in a single game)."

That's how it used to work before we transitioned to the new engine.

(note, if there is only 20 events at the moment, we'll need 8 more blank placeholder events or Chapter 1 will be broken)

**Comment by DragoonHP** [comment]
That's the reason I was repeating events, since the game will crash if we run out of events.

**Comment by DragoonHP** [comment]
Also, we will need more events than 28 (around 40-45) because some events are condition bound.

**Comment by DragoonHP** [comment]
A note; the game will crash at random points now since we don't have enough events. Those need to be added. I will even like to revise my estimate of 40-45 to 56 if possible after looking at all the events file.
