### ISSUE TITLE
Ensure that KPI bars top out at 100

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#141]
See Cara's email,

"While I'm not sure, it also appeared that the varying bars could get "overfull." While they weren't visually overfull, there were some events that should have caused negative reactions, and the bar remained either at or past 100%."

**Comment by DragoonHP** [comment]
KPI bars top out at 100 (except for money)

```
        if new_value > maximum and name != "money":
            new_value = maximum
```
This bit of code ensures that
