### ISSUE TITLE
Game ran out of events too early - day 2

### ISSUE THREAD

**Issue by kwangchow** [NellWatson/Founders-Life--New-Prototype#147]
See screenshot. Can we check the delivery system is in place, we should not be running out of events so early, surely?

![screen shot 2019-03-04 at 21 19 40](https://user-images.githubusercontent.com/7693171/53764067-367a2f00-3ec4-11e9-8bf2-0ded4ac52c83.png)

(Game next ran out on Day 27!)

**Comment by DragoonHP** [comment]
So this was because of a big oopsie on my part. "chapter_default" was being treated as a regular event and so was available in the normal event que.

The new commit fixes that
