### ISSUE TITLE
Reset Game text alignment

### ISSUE THREAD

**Issue by NellInc** [NellWatson/Founders-Life--New-Prototype#148]
The text on the Reset Game warning bar is too large for its box.

https://drive.google.com/file/d/1tnOZDhR3aV0Jwu01h7I7fLC2ivNr8IDj/view?usp=sharing

This also seems to obscure the close box X on Reset Game.

https://drive.google.com/drive/folders/131YCQZM0tMVEyNFfrYvlmhcm4gmaJzmQ

**Comment by DragoonHP** [comment]
It fits perfectly for me. Can you please check Nell and let me know

**Comment by DipeshAggarwal** [comment]
It fits perfectly for me. Can you please check Nell and let me know

**Comment by NellInc** [comment]
Agreed, the Itch version seems fine to me. Thank you!
