### ISSUE TITLE
ToDo create a proper game over screen

### ISSUE THREAD

**Issue by NellInc** [NellWatson/Founders-Life--New-Prototype#152]

**Comment by DragoonHP** [comment]
How should I go about doing this?

**Comment by DipeshAggarwal** [comment]
How should I go about doing this?

**Comment by NellInc** [comment]
Here's an image in 2k, and below it 5k.

Can the Nell character please state the following: "Congratulations! You have endured a long and difficult journey. Your baby venture is now starting to mature. With greater scale will come further challenges, but these too may be overcome. 

For now, this episode has reached its conclusion. Congratulations, once again!"

![iStock-1263707732 (1)](https://user-images.githubusercontent.com/5419314/131924054-71a501d7-cf74-4c0a-b03f-2b17e3fdfa6c.jpg)


![iStock-1263707732 (2)](https://user-images.githubusercontent.com/5419314/131924072-c83509ea-bee7-489f-a5b5-b0ceb0e92cb9.jpg)
