### ISSUE TITLE
Sudden death on New game at 85 days?

### ISSUE THREAD

**Issue by NellInc** [NellWatson/Founders-Life--New-Prototype#154]
https://drive.google.com/drive/folders/1WLwY8VUl4fVp077Ifh_Yc8m_3tTSV6fH

**Comment by DragoonHP** [comment]
It's because player did not have enough affection points. Should we change the text to highlight that?

**Comment by NellInc** [comment]
Ahh, let's explicitly call a game over then! The Nell character can state the following over this image, please:

"Oh dear! Your personal relationships are in tatters, and without the moral support of those closest to you, the grind  becomes unbearable. You give up this misery-generating enterprise and try to get your old job back."

Similarly for running out of resources: 

"It's the final straw. The last of your finances and personal resources are spent, and simply you have no more to give. It's sad that things didn't work out this time, but try, try again."

![iStock-1263707732 (1)](https://user-images.githubusercontent.com/5419314/131923398-ca9d6f76-d5bb-4353-8086-f43cc634ed86.jpg)

Thank you!

**Comment by NellInc** [comment]
5k version if that's any more helpful.

![iStock-1221628675 (1)](https://user-images.githubusercontent.com/5419314/131923964-0424c0c9-2edf-4d80-b829-2881ccabc819.jpg)
