### ISSUE TITLE
Reduce FounderPedia entries

### ISSUE THREAD

**Issue by NellInc** [NellWatson/Founders-Life--New-Prototype#156]
Reduce Founderpedia entries to only Four resources that are all unlocked and accessible by default, but which are *highlighted* after every chapter.

Chapter 1. Double Your Freelancing by Brennan Dunn https://doubleyourfreelancing.com/topics
Chapter 2. Ja-Naé Duane's Startup Equation (link TBC)
Chapter 3. Alex Hillman's Stacking The Bricks https://stackingthebricks.com/articles/
Chapter 4. Nell Watson's Founder life (link TBC)

**Comment by NellInc** [comment]
Essentially, instead of loading up text, I think it's best if it offers an option box that says "Would you like to explore x r?", and if they click yes, open the URL.

**Comment by NellInc** [comment]
Resources: 

1a. Ja-Naé Duane and Steve Fisher's Startup Equation ( https://startupequation.com )

1b. Ja-Naé Duane and Steve Fisher's BASE Board Model for planning an enterprise ( https://www.dropbox.com/s/0qdzkyqev23l50l/Base%20Board%20Model_Workbook.pdf )

1c. Ja-Naé Duane and Steve Fisher's Startup Launch Kits ( https://drive.google.com/drive/folders/0B9wuRcuwU59aaTVIUFdwSFlDOTQ )

2. Alex Hillman et al's Stacking the Bricks resources for entrepreneurs ( https://stackingthebricks.com/articles )

3. Brendan Dunn's Double Your Freelancing resources ( https://doubleyourfreelancing.com/topics )

4. Nell Watson's Founder Life Book (TBC)

**Comment by DipeshAggarwal** [comment]
Should I use the links from your first post or the last post?

**Comment by NellInc** [comment]
Second post please, thank you!
