### ISSUE TITLE
Test if live web play can work hosted via Itch

### ISSUE THREAD

**Issue by NellInc** [NellWatson/Founders-Life--New-Prototype#171]
A prospective entrepreneurial educator was interested in this function. May require some streamlining of assets. Any telemetry likely won't function either.

**Comment by NellInc** [comment]
e.g. https://itch.io/games/newest/html5/made-with-renpy

**Comment by DipeshAggarwal** [comment]
Tested with multiple changes. Probably need to rework the game to make it web compatibele.

Should I bother with it?

**Comment by DipeshAggarwal** [comment]
Sorry somehow I missed it.

I don't know how much work will be required to be quite honest.
We might have to build the game from scratch and add features to it and modify whatever doesn't work with Ren'Py web

**Comment by NellInc** [comment]
Thank you. It might work better than expected, perhaps only requiring compressed assets perhaps.

**Comment by DipeshAggarwal** [comment]
Working
