### ISSUE TITLE
Highlight Skylar, Takashi, and Roger when speaking about them in the intro.

### ISSUE THREAD

**Issue by NellInc** [NellWatson/Founders-Life--New-Prototype#172]
It's a bit odd to talk about the colleagues on the journey without having their image onscreen. If possible, can they be highlighted during the MC's discussion of them, please?

**Comment by DipeshAggarwal** [comment]
How should I highlight them?

**Comment by NellInc** [comment]
Thank you. Please either display the character on its own, or else preferably all three, but blurring or fading the other characters during each respective character overview.

**Comment by DipeshAggarwal** [comment]
We don't have character sprites for the three characters.

**Comment by NellInc** [comment]
I rather mean, if it's possible to somehow keep them onscreen (even as a bg image) whilst the PC talks about them.

**Comment by DipeshAggarwal** [comment]
Okay. So I'll put the circles in there

**Comment by NellInc** [comment]
Great, thank you!
